require("user.conf.which_key")
require("user.conf.todo_comments")
require("user.conf.cmp")
require("user.conf.telescope")
require("user.conf.treesitter")
require("user.conf.autopairs")
require("user.conf.comment")
require("user.conf.gitsigns")
require("user.conf.nvim_tree")
require("user.conf.bufferline")
require("user.conf.lualine")

require("user.conf.indent-blankline")
require("user.conf.impatient")
require("user.conf.alpha")
require("user.conf.hop")
require("user.conf.autosave")
require("user.conf.notify")
-- require("user.conf.sniprun")
